#ifndef INTERFACE_H_
#define INTERFACE_H_
#include"private.h"
#include"Registers.h"
#include"STD.h"


void RCC_setclk_sts(CLK_TYPE clock_type ,STATUS stat);
void RCC_sysclk(SYS_CLK_MUX system_clock);
void RCC_PLLSRC_MUX(CLK_TYPE clock_source);
void RCC_PLLCONFIG(uint8_t PLLM,uint8_t PLLN,uint8_t PLLP,uint8_t PLLQ,uint8_t PLLR);
void RCC_AHB1_ENABLE_PERIPHERAL(RCC_AHB1_PERIPHERAL perph);
void RCC_AHB1_DISBLE_PERIPHERAL(RCC_AHB1_PERIPHERAL perph);
void RCC_AHB2_ENABLE_PERIPHERAL(RCC_AHB2_PERIPHERAL perph);
void RCC_AHB2_DISABLE_PERIPHERAL(RCC_AHB2_PERIPHERAL perph);
void RCC_AHB3_ENABLE_PERIPHERAL(RCC_AHB3_PERIPHERAL perph);
void RCC_AHB3_DISABLE_PERIPHERAL(RCC_AHB3_PERIPHERAL perph);
void RCC_APB1_ENABLE_PERIPHERAL(RCC_APB1_PERIPHERAL perph);
void RCC_APB1_DISABLE_PERIPHERAL(RCC_APB1_PERIPHERAL perph);
void RCC_APB2_ENABLE_PERIPHERAL(RCC_APB2_PERIPHERAL perph);
void RCC_APB2_DISABLE_PERIPHERAL(RCC_APB2_PERIPHERAL perph);



#endif /* INTERFACE_H_ */
