#include<stdint.h>
#include"private.h"
#include"Registers.h"
#include"STD.h"

/********SET CLOCK TYPE*********/

void RCC_setclk_sts(CLK_TYPE clock_type ,STATUS stat)
{
	uint16_t time=0;
	switch(clock_type)
	{
	case HSI:
		if(stat==ON)
		{
			RCC->CR.BIT.HSION=ON;
			while(time<TIMEOUT&&RCC->CR.BIT.HSIRDY==OFF)
			{
				time++;
			}
		}

		else if(stat==OFF)
		{
			RCC->CR.BIT.HSION=OFF;
		}
		break;
	case HSE:
		if(stat==ON)
		{
			RCC->CR.BIT.HSEON=ON;
			while(time<TIMEOUT&&RCC->CR.BIT.HSERDY==OFF)
			{
				time++;
			}
		}

		else if(stat==OFF)
		{
			RCC->CR.BIT.HSEON=OFF;
		}
		break;
	case PLL:
		if(stat==ON)
		{
			RCC->CR.BIT.PLLON=ON;
			while(RCC->CR.BIT.PLLRDY==OFF&&time<=TIMEOUT)
			{
				time++;
			}
		}
		else if(stat==OFF)
		{
			RCC->CR.BIT.PLLON=OFF;
		}

		break;

		/*	case PLLSAI:
		if(stat==ON)
		{
			RCC->CR.BIT.PLLSAION=ON;
			while(RCC->CR.BIT.PLLSAIRDY==OFF&&time<=TIMEOUT)
			{
				time++;
			}
		}
		else if(stat==OFF)
		{
			RCC->CR.BIT.PLLSAION=OFF;
		}
		break;

	case PLLI2S:
		if(stat==ON)
		{
			RCC->CR.BIT.PLLI2SON=ON;
			while(RCC->CR.BIT.PLLI2SON==OFF&&time<=TIMEOUT)
			{
				time++;
			}
		}
		else if(stat==OFF)
		{
			RCC->CR.BIT.PLLI2SON=OFF;
		}

		break;*/
	}
}


/********SET SYSTEM CLOCK SOURCE********/

void RCC_sysclk(SYS_CLK_MUX system_clock)
{
	switch(system_clock)
	{
	case HSI:
		RCC->CFGR.BIT.SW=0b00;
		break;
	case HSE:
		RCC->CFGR.BIT.SW=0b01;
		break;
	case PLLP:
		RCC->CFGR.BIT.SW=0b10;
		break;
	case PLLR:
		RCC->CFGR.BIT.SW=0b11;
		break;
	}
}


/*********SELECT PLL CLOCK SOURCE********/
void RCC_PLLSRC_MUX(CLK_TYPE clock_source)
{
	if(clock_source==HSI)
	{
		RCC->PLLCFGR.BIT.PLLSRC=0;
	}
	else if(clock_source==HSE)
	{
		RCC->PLLCFGR.BIT.PLLSRC=1;
	}

}

/*********PLL_CONFIG**********/

void RCC_PLLCONFIG(uint8_t PLLM,uint8_t PLLN,uint8_t PLLP,uint8_t PLLQ,uint8_t PLLR)
{
	RCC->PLLCFGR.BIT.PLLM=PLLM;
	RCC->PLLCFGR.BIT.PLLN=PLLN;
	RCC->PLLCFGR.BIT.PLLP=PLLP;
	RCC->PLLCFGR.BIT.PLLQ=PLLQ;
	RCC->PLLCFGR.BIT.PLLR=PLLR;
}



/***************ENABLE_PERIPHERALS****************/
void RCC_AHB1_ENABLE_PERIPHERAL(RCC_AHB1_PERIPHERAL perph)
{
	switch(perph)
	{
	case GPIOAEN:
		RCC->AHB1ENR.BIT.GPIOAEN=ON;
	case GPIOBEN:
		RCC->AHB1ENR.BIT.GPIOBEN=ON;
	case GPIOCEN:
		RCC->AHB1ENR.BIT.GPIOCEN=ON;
	case GPIODEN:
		RCC->AHB1ENR.BIT.GPIODEN=ON;
	case GPIOEEN:
		RCC->AHB1ENR.BIT.GPIOEEN=ON;
	case GPIOFEN:
		RCC->AHB1ENR.BIT.GPIOFEN=ON;
	case GPIOGEN:
		RCC->AHB1ENR.BIT.GPIOGEN=ON;
	case GPIOHEN:
		RCC->AHB1ENR.BIT.GPIOHEN=ON;
	case CRCEN:
		RCC->AHB1ENR.BIT.CRCEN=ON;
	case BKPSRAMEN:
		RCC->AHB1ENR.BIT.BKPSRAMEN=ON;
	case DMA1EN:
		RCC->AHB1ENR.BIT.DMA1EN=ON;
	case DMA2EN:
		RCC->AHB1ENR.BIT.DMA2EN=ON;
	case OTGHSEN:
		RCC->AHB1ENR.BIT.OTGHSEN=ON;
	case OTGHSULPIEN:
		RCC->AHB1ENR.BIT.OTGHSULPIEN=ON;
	}
}



void RCC_AHB1_DISBLE_PERIPHERAL(RCC_AHB1_PERIPHERAL perph)
{
	switch(perph)
	{
	case GPIOAEN:
		RCC->AHB1ENR.BIT.GPIOAEN=OFF;
	case GPIOBEN:
		RCC->AHB1ENR.BIT.GPIOBEN=OFF;
	case GPIOCEN:
		RCC->AHB1ENR.BIT.GPIOCEN=OFF;
	case GPIODEN:
		RCC->AHB1ENR.BIT.GPIODEN=OFF;
	case GPIOEEN:
		RCC->AHB1ENR.BIT.GPIOEEN=OFF;
	case GPIOFEN:
		RCC->AHB1ENR.BIT.GPIOFEN=OFF;
	case GPIOGEN:
		RCC->AHB1ENR.BIT.GPIOGEN=OFF;
	case GPIOHEN:
		RCC->AHB1ENR.BIT.GPIOHEN=OFF;
	case CRCEN:
		RCC->AHB1ENR.BIT.CRCEN=OFF;
	case BKPSRAMEN:
		RCC->AHB1ENR.BIT.BKPSRAMEN=OFF;
	case DMA1EN:
		RCC->AHB1ENR.BIT.DMA1EN=OFF;
	case DMA2EN:
		RCC->AHB1ENR.BIT.DMA2EN=OFF;
	case OTGHSEN:
		RCC->AHB1ENR.BIT.OTGHSEN=OFF;
	case OTGHSULPIEN:
		RCC->AHB1ENR.BIT.OTGHSULPIEN=OFF;
	}
}



void RCC_AHB2_ENABLE_PERIPHERAL(RCC_AHB2_PERIPHERAL perph)
{
	switch(perph)
	{
	case DCMIEN:
		RCC->AHB2ENR.BIT.DCMIEN=ON;
	case OTGFSEN:
			RCC->AHB2ENR.BIT.OTGFSEN=ON;


	}
}

void RCC_AHB2_DISABLE_PERIPHERAL(RCC_AHB2_PERIPHERAL perph)
{
	switch(perph)
	{
	case DCMIEN:
		RCC->AHB2ENR.BIT.DCMIEN=OFF;
	case OTGFSEN:
			RCC->AHB2ENR.BIT.OTGFSEN=OFF;
	}
}



void RCC_AHB3_ENABLE_PERIPHERAL(RCC_AHB3_PERIPHERAL perph)
{
	switch(perph)
	{
	case FMCEN:
		RCC->AHB3ENR.BIT.FMCEN=ON;
	case QSPIEN:
			RCC->AHB3ENR.BIT.QSPIEN=ON;
	}
}

void RCC_AHB3_DISABLE_PERIPHERAL(RCC_AHB3_PERIPHERAL perph)
{
	switch(perph)
	{
	case FMCEN:
		RCC->AHB3ENR.BIT.FMCEN=OFF;
	case QSPIEN:
			RCC->AHB3ENR.BIT.QSPIEN=OFF;
	}
}




void RCC_APB1_ENABLE_PERIPHERAL(RCC_APB1_PERIPHERAL perph){
	switch(perph)
	{
	case TIM2EN:
		RCC->APB1ENR.BIT.TIM2EN=ON;
	case TIM3EN:
			RCC->APB1ENR.BIT.TIM3EN=ON;
	case TIM4EN:
				RCC->APB1ENR.BIT.TIM4EN=ON;
	case TIM5EN:
				RCC->APB1ENR.BIT.TIM5EN=ON;
	case TIM6EN:
				RCC->APB1ENR.BIT.TIM6EN=ON;
	case TIM7EN:
			RCC->APB1ENR.BIT.TIM7EN=ON;
	case TIM12EN:
				RCC->APB1ENR.BIT.TIM12EN=ON;
	case TIM13EN:
				RCC->APB1ENR.BIT.TIM13EN=ON;
	case TIM14EN:
				RCC->APB1ENR.BIT.TIM14EN=ON;
	case WWDGEN:
			RCC->APB1ENR.BIT.WWDGEN=ON;
	case SPI2EN:
				RCC->APB1ENR.BIT.SPI2EN=ON;
	case SPI3EN:
				RCC->APB1ENR.BIT.SPI3EN=ON;
	case SPDIFRXEN:
				RCC->APB1ENR.BIT.SPDIFRXEN=ON;
	case USART2EN:
			RCC->APB1ENR.BIT.USART2EN=ON;
	case USART3EN:
				RCC->APB1ENR.BIT.USART3EN=ON;
	case UART4EN:
				RCC->APB1ENR.BIT.UART4EN=ON;
	case UART5EN:
				RCC->APB1ENR.BIT.UART5EN=ON;
	case I2C1EN:
			RCC->APB1ENR.BIT.I2C1EN=ON;
	case I2C2EN:
				RCC->APB1ENR.BIT.I2C2EN=ON;
	case I2C3EN:
				RCC->APB1ENR.BIT.I2C3EN=ON;
	case FMPI2C1EN:
				RCC->APB1ENR.BIT.FMPI2C1EN=ON;
	case CAN1EN:
			RCC->APB1ENR.BIT.CAN1EN=ON;
	case CAN2EN:
				RCC->APB1ENR.BIT.CAN2EN=ON;
	case CECEN:
				RCC->APB1ENR.BIT.CECEN=ON;
	case PWREN:
				RCC->APB1ENR.BIT.PWREN=ON;
	case DACEN:
			RCC->APB1ENR.BIT.DACEN=ON;

	}
}


void RCC_APB1_DISABLE_PERIPHERAL(RCC_APB1_PERIPHERAL perph){
	switch(perph)
	{
	case TIM2EN:
		RCC->APB1ENR.BIT.TIM2EN=OFF;
	case TIM3EN:
			RCC->APB1ENR.BIT.TIM3EN=OFF;
	case TIM4EN:
				RCC->APB1ENR.BIT.TIM4EN=OFF;
	case TIM5EN:
				RCC->APB1ENR.BIT.TIM5EN=OFF;
	case TIM6EN:
				RCC->APB1ENR.BIT.TIM6EN=OFF;
	case TIM7EN:
			RCC->APB1ENR.BIT.TIM7EN=OFF;
	case TIM12EN:
				RCC->APB1ENR.BIT.TIM12EN=OFF;
	case TIM13EN:
				RCC->APB1ENR.BIT.TIM13EN=OFF;
	case TIM14EN:
				RCC->APB1ENR.BIT.TIM14EN=OFF;
	case WWDGEN:
			RCC->APB1ENR.BIT.WWDGEN=OFF;
	case SPI2EN:
				RCC->APB1ENR.BIT.SPI2EN=OFF;
	case SPI3EN:
				RCC->APB1ENR.BIT.SPI3EN=OFF;
	case SPDIFRXEN:
				RCC->APB1ENR.BIT.SPDIFRXEN=OFF;
	case USART2EN:
			RCC->APB1ENR.BIT.USART2EN=OFF;
	case USART3EN:
				RCC->APB1ENR.BIT.USART3EN=OFF;
	case UART4EN:
				RCC->APB1ENR.BIT.UART4EN=OFF;
	case UART5EN:
				RCC->APB1ENR.BIT.UART5EN=OFF;
	case I2C1EN:
			RCC->APB1ENR.BIT.I2C1EN=OFF;
	case I2C2EN:
				RCC->APB1ENR.BIT.I2C2EN=OFF;
	case I2C3EN:
				RCC->APB1ENR.BIT.I2C3EN=OFF;
	case FMPI2C1EN:
				RCC->APB1ENR.BIT.FMPI2C1EN=OFF;
	case CAN1EN:
			RCC->APB1ENR.BIT.CAN1EN=OFF;
	case CAN2EN:
				RCC->APB1ENR.BIT.CAN2EN=OFF;
	case CECEN:
				RCC->APB1ENR.BIT.CECEN=OFF;
	case PWREN:
				RCC->APB1ENR.BIT.PWREN=OFF;
	case DACEN:
			RCC->APB1ENR.BIT.DACEN=OFF;

	}
}



void RCC_APB2_ENABLE_PERIPHERAL(RCC_APB2_PERIPHERAL perph)
{
	switch(perph)
	{
	case TIM8EN:
		RCC->APB2ENR.BIT.TIM8EN=ON;
	case TIM1EN:
			RCC->APB2ENR.BIT.TIM1EN=ON;
	case USART1EN:
			RCC->APB2ENR.BIT.USART1EN=ON;
	case USART6EN:
			RCC->APB2ENR.BIT.USART6EN=ON;
	case ADC1EN:
			RCC->APB2ENR.BIT.ADC1EN=ON;
	case ADC2EN:
			RCC->APB2ENR.BIT.ADC2EN=ON;
	case ADC3EN:
			RCC->APB2ENR.BIT.ADC3EN=ON;
	case SDIOEN:
			RCC->APB2ENR.BIT.SDIOEN=ON;
	case SPI1EN:
			RCC->APB2ENR.BIT.SPI1EN=ON;
	case SPI4EN:
			RCC->APB2ENR.BIT.SPI4EN=ON;
	case SYSCFGEN:
			RCC->APB2ENR.BIT.SYSCFGEN=ON;
	case TIM9EN:
			RCC->APB2ENR.BIT.TIM9EN=ON;
	case TIM10EN:
			RCC->APB2ENR.BIT.TIM10EN=ON;
	case TIM11EN:
				RCC->APB2ENR.BIT.TIM11EN=ON;

	case SAI1EN:
				RCC->APB2ENR.BIT.SAI1EN=ON;

	case SAI2EN:
				RCC->APB2ENR.BIT.SAI2EN=ON;


	}
}


void RCC_APB2_DISABLE_PERIPHERAL(RCC_APB2_PERIPHERAL perph)
{
	switch(perph)
	{
	case TIM8EN:
		RCC->APB2ENR.BIT.TIM8EN=OFF;
	case TIM1EN:
			RCC->APB2ENR.BIT.TIM1EN=OFF;
	case USART1EN:
			RCC->APB2ENR.BIT.USART1EN=OFF;
	case USART6EN:
			RCC->APB2ENR.BIT.USART6EN=OFF;
	case ADC1EN:
			RCC->APB2ENR.BIT.ADC1EN=OFF;
	case ADC2EN:
			RCC->APB2ENR.BIT.ADC2EN=OFF;
	case ADC3EN:
			RCC->APB2ENR.BIT.ADC3EN=OFF;
	case SDIOEN:
			RCC->APB2ENR.BIT.SDIOEN=OFF;
	case SPI1EN:
			RCC->APB2ENR.BIT.SPI1EN=OFF;
	case SPI4EN:
			RCC->APB2ENR.BIT.SPI4EN=OFF;
	case SYSCFGEN:
			RCC->APB2ENR.BIT.SYSCFGEN=OFF;
	case TIM9EN:
			RCC->APB2ENR.BIT.TIM9EN=OFF;
	case TIM10EN:
			RCC->APB2ENR.BIT.TIM10EN=OFF;
	case TIM11EN:
				RCC->APB2ENR.BIT.TIM11EN=OFF;

	case SAI1EN:
				RCC->APB2ENR.BIT.SAI1EN=OFF;

	case SAI2EN:
				RCC->APB2ENR.BIT.SAI2EN=OFF;


	}
}




